default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres


development:
  <<: *default
  database: demo_app_development

test:
  <<: *default
  database: demo_app_test

production:
  <<: *default
  database: demo_app_production
  username: demo_app
  password: <%= ENV["DEMO_APP_DATABASE_PASSWORD"] %>
